### ISSUE TITLE
error: borrow of packed field requires unsafe function or block (error E0133)

### ISSUE THREAD

**Issue by sajattack** [redox-os/redoxfs#36]
As of rust 1.24 packed fields cannot be borrowed safely. Options are to remove `repr(packed)` if it's not needed or to copy fields to a local variable. See https://github.com/rust-lang/rust/issues/46043 for more details.

**Comment by jackpot51** [comment]
Well that is certainly annoying

**Comment by vladimiroff** [comment]
f206dab653f34a7362c5050fce0e637e17c64004 fixes this so I think it's okay to close the issue.
